/* Generated By:JavaCC: Do not edit this line. KarloffConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface KarloffConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int MAIN = 5;
  /** RegularExpression Id. */
  int ACHAVES = 6;
  /** RegularExpression Id. */
  int FCHAVES = 7;
  /** RegularExpression Id. */
  int APARENTESES = 8;
  /** RegularExpression Id. */
  int FPARENTESES = 9;
  /** RegularExpression Id. */
  int VOID = 10;
  /** RegularExpression Id. */
  int FLOAT = 11;
  /** RegularExpression Id. */
  int NEWVAR = 12;
  /** RegularExpression Id. */
  int PRINTOUT = 13;
  /** RegularExpression Id. */
  int TRUE = 14;
  /** RegularExpression Id. */
  int FALSE = 15;
  /** RegularExpression Id. */
  int BOOLEAN = 16;
  /** RegularExpression Id. */
  int FUNCTION = 17;
  /** RegularExpression Id. */
  int WHILE = 18;
  /** RegularExpression Id. */
  int IF = 19;
  /** RegularExpression Id. */
  int THEN = 20;
  /** RegularExpression Id. */
  int RETURN = 21;
  /** RegularExpression Id. */
  int ATRIBUICAO = 22;
  /** RegularExpression Id. */
  int PONTOVIRGULA = 23;
  /** RegularExpression Id. */
  int PONTO = 24;
  /** RegularExpression Id. */
  int SOMA = 25;
  /** RegularExpression Id. */
  int SUB = 26;
  /** RegularExpression Id. */
  int MULT = 27;
  /** RegularExpression Id. */
  int DIV = 28;
  /** RegularExpression Id. */
  int AND = 29;
  /** RegularExpression Id. */
  int OR = 30;
  /** RegularExpression Id. */
  int MAIORQUE = 31;
  /** RegularExpression Id. */
  int MENORQUE = 32;
  /** RegularExpression Id. */
  int IGUAL = 33;
  /** RegularExpression Id. */
  int READINPUT = 34;
  /** RegularExpression Id. */
  int VIRGULA = 35;
  /** RegularExpression Id. */
  int TOKEN_LITERAL = 36;
  /** RegularExpression Id. */
  int TOKEN_ID = 37;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"main\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\"void\"",
    "\"float\"",
    "\"newVar\"",
    "\"printOut\"",
    "\"true\"",
    "\"false\"",
    "\"bool\"",
    "\"fun\"",
    "\"while\"",
    "\"if\"",
    "\"then\"",
    "\"return\"",
    "\"=\"",
    "\";\"",
    "\".\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&\"",
    "\"|\"",
    "\">\"",
    "\"<\"",
    "\"==\"",
    "\"readInput\"",
    "\",\"",
    "<TOKEN_LITERAL>",
    "<TOKEN_ID>",
  };

}
